/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface EiFiLibraryInterface extends ethers.utils.Interface {
  functions: {
    "getFeeValue(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getFeeValue", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getFeeValue",
    data: BytesLike
  ): Result;

  events: {};
}

export class EiFiLibrary extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EiFiLibraryInterface;

  functions: {
    getFeeValue(
      factory: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getFeeValue(address)"(
      factory: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getFeeValue(factory: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getFeeValue(address)"(
    factory: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getFeeValue(factory: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getFeeValue(address)"(
      factory: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getFeeValue(factory: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getFeeValue(address)"(
      factory: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFeeValue(
      factory: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFeeValue(address)"(
      factory: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
