/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { EiFiLibrary } from "../EiFiLibrary";

export class EiFiLibrary__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EiFiLibrary> {
    return super.deploy(overrides || {}) as Promise<EiFiLibrary>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EiFiLibrary {
    return super.attach(address) as EiFiLibrary;
  }
  connect(signer: Signer): EiFiLibrary__factory {
    return super.connect(signer) as EiFiLibrary__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EiFiLibrary {
    return new Contract(address, _abi, signerOrProvider) as EiFiLibrary;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
    ],
    name: "getFeeValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x610126610026600b82828239805160001a60731461001957fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806338a964d6146038575b600080fd5b605b60048036036020811015604c57600080fd5b50356001600160a01b0316606d565b60408051918252519081900360200190f35b60006103e8826001600160a01b0316639fddaa936040518163ffffffff1660e01b815260040160206040518083038186803b15801560aa57600080fd5b505afa15801560bd573d6000803e3d6000fd5b505050506040513d602081101560d257600080fd5b505162ffffff168160df57fe5b046103e80362ffffff16905091905056fea2646970667358221220963192b0dfff641c06513f15650622686ac8d38c389ac2526d5d31a32978f55164736f6c63430007060033";
