/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IEIFIReferralInterface extends ethers.utils.Interface {
  functions: {
    "getReferrer(address)": FunctionFragment;
    "recordReferral(address,address)": FunctionFragment;
    "recordReferralCommission(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getReferrer", values: [string]): string;
  encodeFunctionData(
    functionFragment: "recordReferral",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordReferralCommission",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordReferralCommission",
    data: BytesLike
  ): Result;

  events: {};
}

export class IEIFIReferral extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IEIFIReferralInterface;

  functions: {
    getReferrer(user: string, overrides?: CallOverrides): Promise<[string]>;

    "getReferrer(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    recordReferral(
      user: string,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "recordReferral(address,address)"(
      user: string,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    recordReferralCommission(
      referrer: string,
      commission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "recordReferralCommission(address,uint256)"(
      referrer: string,
      commission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getReferrer(user: string, overrides?: CallOverrides): Promise<string>;

  "getReferrer(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<string>;

  recordReferral(
    user: string,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "recordReferral(address,address)"(
    user: string,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  recordReferralCommission(
    referrer: string,
    commission: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "recordReferralCommission(address,uint256)"(
    referrer: string,
    commission: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getReferrer(user: string, overrides?: CallOverrides): Promise<string>;

    "getReferrer(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<string>;

    recordReferral(
      user: string,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "recordReferral(address,address)"(
      user: string,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    recordReferralCommission(
      referrer: string,
      commission: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "recordReferralCommission(address,uint256)"(
      referrer: string,
      commission: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getReferrer(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getReferrer(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordReferral(
      user: string,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "recordReferral(address,address)"(
      user: string,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    recordReferralCommission(
      referrer: string,
      commission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "recordReferralCommission(address,uint256)"(
      referrer: string,
      commission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getReferrer(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReferrer(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recordReferral(
      user: string,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "recordReferral(address,address)"(
      user: string,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    recordReferralCommission(
      referrer: string,
      commission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "recordReferralCommission(address,uint256)"(
      referrer: string,
      commission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
