/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MigrateLPInterface extends ethers.utils.Interface {
  functions: {
    "desiredLiquidity()": FunctionFragment;
    "factory()": FunctionFragment;
    "migrate(address)": FunctionFragment;
    "oldFactory()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "desiredLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "migrate", values: [string]): string;
  encodeFunctionData(
    functionFragment: "oldFactory",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "desiredLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oldFactory", data: BytesLike): Result;

  events: {};
}

export class MigrateLP extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MigrateLPInterface;

  functions: {
    desiredLiquidity(overrides?: CallOverrides): Promise<[BigNumber]>;

    "desiredLiquidity()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    "factory()"(overrides?: CallOverrides): Promise<[string]>;

    migrate(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "migrate(address)"(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    oldFactory(overrides?: CallOverrides): Promise<[string]>;

    "oldFactory()"(overrides?: CallOverrides): Promise<[string]>;
  };

  desiredLiquidity(overrides?: CallOverrides): Promise<BigNumber>;

  "desiredLiquidity()"(overrides?: CallOverrides): Promise<BigNumber>;

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  migrate(
    orig: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "migrate(address)"(
    orig: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  oldFactory(overrides?: CallOverrides): Promise<string>;

  "oldFactory()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    desiredLiquidity(overrides?: CallOverrides): Promise<BigNumber>;

    "desiredLiquidity()"(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    migrate(orig: string, overrides?: CallOverrides): Promise<string>;

    "migrate(address)"(
      orig: string,
      overrides?: CallOverrides
    ): Promise<string>;

    oldFactory(overrides?: CallOverrides): Promise<string>;

    "oldFactory()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    desiredLiquidity(overrides?: CallOverrides): Promise<BigNumber>;

    "desiredLiquidity()"(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    migrate(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "migrate(address)"(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    oldFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "oldFactory()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    desiredLiquidity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "desiredLiquidity()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrate(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "migrate(address)"(
      orig: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    oldFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "oldFactory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
